max_results = 25

# Directory to search for files from
search_paths = ["/home/dias"]
search_hidden_folders = false

# Directories to ignore when indexing and searching files.
ignore_directories = ["node_modules", "zig-cache", "zig-out", "target", "_prefix32_wine", "texmf", "VirtualBox VMs", "x86_64-pc-linux-gnu-library", "x86_64-unknown-linux-gnu-library"]

# Index and search files by keywords they contain. Works for pdf, docx,
# txt and a few other plaintext filetypes. Will take considerably longer
# to index. It is recommended that full reindexes are done infrequently
# with this option.
search_file_contents = false

[indexing]

# Where to store the file database.
location = "/home/dias/.cache/glimpse"

# The maximum size of the file index database in GiB. If this is exceeded,
# new data will not be added until there has been a full reindex.
size_upper_bound_GiB = 5.0

# Recrawl and reindex the file system after this many days
full_reindex_after_days = 0.6000000238418579

[modules]
commands = true
files = true
steam_games = true
web_bookmarks = true
calculator = true
dictionary = false

[visual]
show_icons = true
icon_size = 32
result_borders = false
dark_result_borders = false

[window]
width = 540
height = 410

[preview_window]
enabled = true
width = 420
image_size = 350

[misc]
display_command_paths = false
display_file_and_directory_paths = true
preferred_terminal = "xterm"

# Open files with a .exe extension with wine.
run_exes_with_wine = true
